version: '3.8'

services:
  postgres:
    container_name: postgres_container
    build: ./
    env_file:
        - .env
    volumes:
        - postgres:/data/postgres
    ports:
        - "5432:5432"
    networks:
        - acmesky
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4:5.4
#    env_file:
#        - .env
#    volumes:
#        - pgadmin:/root/.pgadmin
#    ports:
#        - "5050:80"
#    networks:
#        - acmesky
#    restart: unless-stopped

networks:
    acmesky:
        driver: bridge
        name: acmesky-net

volumes:
    postgres:
    pgadmin: