version: '3.9'

services:
    acmesky:
        container_name: bank_container
        build: ./
        env_file:
            - .env
        ports:
            - "8070:8080"
        networks:
            - acmesky
        restart: unless-stopped
    
            
networks:
    acmesky:
        external: true
        name: acmesky-net

volumes:
    acmesky: