version: '3.9'

services:
    acmesky:
        container_name: acmesky_container
        build: ./src/ACMEskyService
        env_file:
            - ./src/ACMEskyService/.env
        ports:
            - "8080:8080"
        networks:
            - acmesky
        restart: unless-stopped
        depends_on:
            - postgres

    postgres:
        container_name: postgres_container
        build: ./src/ACMEskyDB
        env_file:
            - ./src/ACMEskyDB/.env
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - acmesky
        restart: unless-stopped
    
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.4
        env_file:
            - ./src/ACMEskyDB/.env
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"
        networks:
            - acmesky
        restart: unless-stopped
        depends_on:
            - postgres
    
    web:
        container_name: acmesky_web
        build: ./src/ACMEskyWeb
        volumes:
            - ./src/ACMEskyWeb/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        networks:
            - acmesky
        restart: unless-stopped
        depends_on:
            - acmesky
            
networks:
    acmesky:
        driver: bridge
        name: acmesky-net

volumes:

    postgres:
    pgadmin: