version: '3.9'

services:
    geo_distance:
        container_name: geo_distance_container
        build: ./
        env_file:
            - .env
        ports:
            - "8040:80"
        restart: unless-stopped
        networks: 
            - acmesky

networks:
    acmesky:
        external: true
        name: acmesky-net