version: '3.9'

services:
    geodistance:
        container_name: geodistance_container
        build: ./
        env_file:
            - .env
        ports:
            - "8040:80"
        restart: always
        networks: 
            - acmesky

networks:
    acmesky:
        external: true
        name: acmesky-net