version: '3.9'

services:
    acmesky:
        container_name: acmesky_container
        build: ./
        env_file:
            - .env
        ports:
            - "8080:8080"
        networks:
            - acmesky
        restart: unless-stopped
    
networks:
    acmesky:
        external: true
        name: acmesky-net