version: "3"
services:
    national-airline:
        container_name: national-service
        build: "."
        # lista delle variabili di environment
        env_file: ./AirlineCredentialsEnvFiles/CredentialsAirline1.env
        volumes: 
            - ./db:/db
            - ./fileSampleOffers/NationalFlights.json:/list/list.json
             # espongo le porte (come -p su docker)
        ports:
            - 8060:8082
        networks:
            - acmesky
    # uguale per tutti gli altri servizi
    international-airline:
        container_name: international-service
        build: "."
        env_file: ./AirlineCredentialsEnvFiles/CredentialsAirline2.env
        volumes:
        # riferimento della cartella db nell'host
        # all'interno della cartella "/db" nel container
            - ./db:/db
            - ./fileSampleOffers/InternationalFlights.json:/list/list.json
        ports:
            - 8061:8082
        networks: 
            - acmesky

networks:
    acmesky:
        external: true
        name: acmesky-net